version: '3.8'

services:
  # PostgreSQL service for relational data
  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ifood
      POSTGRES_DB: ifood_reviews

  # MongoDB service for NoSQL data
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  postgres_data:
  mongo_data:
