spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/ifood_reviews?authSource=admin
      database: ifood_reviews
  datasource:
    url: jdbc:postgresql://localhost:5432/ifood_reviews
    username: ifood
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 151
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect